language: node_js
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
node_js:
  - "8"
install:
  - yarn --pure-lockfile
script:
  - yarn run build
  - yarn run test
cache:
  yarn: true
  directories:
    - node_modules
    - ./**/node_modules
