// Code generated by Prisma (prisma@1.18.0-beta.12). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode, GraphQLSchema } from "graphql";
import { IResolvers } from "graphql-tools/dist/Interfaces";
import { makePrismaClientClass, BaseClientOptions } from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export interface Exists {
  statusScrape: (where?: StatusScrapeWhereInput) => Promise<boolean>;
  statusScrapeResult: (
    where?: StatusScrapeResultWhereInput
  ) => Promise<boolean>;
  statusScrapeTarget: (
    where?: StatusScrapeTargetWhereInput
  ) => Promise<boolean>;
  user: (where?: UserWhereInput) => Promise<boolean>;
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable;

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;
  $getAbstractResolvers(filterSchema?: GraphQLSchema | string): IResolvers;

  /**
   * Queries
   */

  statusScrape: (where: StatusScrapeWhereUniqueInput) => StatusScrape;
  statusScrapes: (
    args?: {
      where?: StatusScrapeWhereInput;
      orderBy?: StatusScrapeOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<StatusScrapeNode>;
  statusScrapesConnection: (
    args?: {
      where?: StatusScrapeWhereInput;
      orderBy?: StatusScrapeOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => StatusScrapeConnection;
  statusScrapeResults: (
    args?: {
      where?: StatusScrapeResultWhereInput;
      orderBy?: StatusScrapeResultOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<StatusScrapeResultNode>;
  statusScrapeResultsConnection: (
    args?: {
      where?: StatusScrapeResultWhereInput;
      orderBy?: StatusScrapeResultOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => StatusScrapeResultConnection;
  statusScrapeTarget: (
    where: StatusScrapeTargetWhereUniqueInput
  ) => StatusScrapeTarget;
  statusScrapeTargets: (
    args?: {
      where?: StatusScrapeTargetWhereInput;
      orderBy?: StatusScrapeTargetOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<StatusScrapeTargetNode>;
  statusScrapeTargetsConnection: (
    args?: {
      where?: StatusScrapeTargetWhereInput;
      orderBy?: StatusScrapeTargetOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => StatusScrapeTargetConnection;
  user: (where: UserWhereUniqueInput) => User;
  users: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<UserNode>;
  usersConnection: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => UserConnection;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createStatusScrape: (data: StatusScrapeCreateInput) => StatusScrape;
  updateStatusScrape: (
    args: { data: StatusScrapeUpdateInput; where: StatusScrapeWhereUniqueInput }
  ) => StatusScrape;
  updateManyStatusScrapes: (
    args: { data: StatusScrapeUpdateInput; where?: StatusScrapeWhereInput }
  ) => BatchPayload;
  upsertStatusScrape: (
    args: {
      where: StatusScrapeWhereUniqueInput;
      create: StatusScrapeCreateInput;
      update: StatusScrapeUpdateInput;
    }
  ) => StatusScrape;
  deleteStatusScrape: (where: StatusScrapeWhereUniqueInput) => StatusScrape;
  deleteManyStatusScrapes: (where?: StatusScrapeWhereInput) => BatchPayload;
  createStatusScrapeResult: (
    data: StatusScrapeResultCreateInput
  ) => StatusScrapeResult;
  updateManyStatusScrapeResults: (
    args: {
      data: StatusScrapeResultUpdateInput;
      where?: StatusScrapeResultWhereInput;
    }
  ) => BatchPayload;
  deleteManyStatusScrapeResults: (
    where?: StatusScrapeResultWhereInput
  ) => BatchPayload;
  createStatusScrapeTarget: (
    data: StatusScrapeTargetCreateInput
  ) => StatusScrapeTarget;
  updateStatusScrapeTarget: (
    args: {
      data: StatusScrapeTargetUpdateInput;
      where: StatusScrapeTargetWhereUniqueInput;
    }
  ) => StatusScrapeTarget;
  updateManyStatusScrapeTargets: (
    args: {
      data: StatusScrapeTargetUpdateInput;
      where?: StatusScrapeTargetWhereInput;
    }
  ) => BatchPayload;
  upsertStatusScrapeTarget: (
    args: {
      where: StatusScrapeTargetWhereUniqueInput;
      create: StatusScrapeTargetCreateInput;
      update: StatusScrapeTargetUpdateInput;
    }
  ) => StatusScrapeTarget;
  deleteStatusScrapeTarget: (
    where: StatusScrapeTargetWhereUniqueInput
  ) => StatusScrapeTarget;
  deleteManyStatusScrapeTargets: (
    where?: StatusScrapeTargetWhereInput
  ) => BatchPayload;
  createUser: (data: UserCreateInput) => User;
  updateUser: (
    args: { data: UserUpdateInput; where: UserWhereUniqueInput }
  ) => User;
  updateManyUsers: (
    args: { data: UserUpdateInput; where?: UserWhereInput }
  ) => BatchPayload;
  upsertUser: (
    args: {
      where: UserWhereUniqueInput;
      create: UserCreateInput;
      update: UserUpdateInput;
    }
  ) => User;
  deleteUser: (where: UserWhereUniqueInput) => User;
  deleteManyUsers: (where?: UserWhereInput) => BatchPayload;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  statusScrape: (
    where?: StatusScrapeSubscriptionWhereInput
  ) => StatusScrapeSubscriptionPayloadSubscription;
  statusScrapeResult: (
    where?: StatusScrapeResultSubscriptionWhereInput
  ) => StatusScrapeResultSubscriptionPayloadSubscription;
  statusScrapeTarget: (
    where?: StatusScrapeTargetSubscriptionWhereInput
  ) => StatusScrapeTargetSubscriptionPayloadSubscription;
  user: (
    where?: UserSubscriptionWhereInput
  ) => UserSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type SystemStatus = "OPERATIONAL" | "UNKNOWN";

export type ScrapeStrategy = "STATUSPAGE_IO";

export type StatusScrapeOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "failed_ASC"
  | "failed_DESC"
  | "dom_ASC"
  | "dom_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type StatusScrapeResultOrderByInput =
  | "category_ASC"
  | "category_DESC"
  | "component_ASC"
  | "component_DESC"
  | "status_ASC"
  | "status_DESC"
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type StatusScrapeTargetOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "twitterHandle_ASC"
  | "twitterHandle_DESC"
  | "strategy_ASC"
  | "strategy_DESC"
  | "statusUrl_ASC"
  | "statusUrl_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type UserOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "email_ASC"
  | "email_DESC"
  | "password_ASC"
  | "password_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export interface StatusScrapeResultCreateManyWithoutScrapeInput {
  create?:
    | StatusScrapeResultCreateWithoutScrapeInput[]
    | StatusScrapeResultCreateWithoutScrapeInput;
}

export type StatusScrapeWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface StatusScrapeTargetUpdateWithoutResultsDataInput {
  name?: String;
  twitterHandle?: String;
  strategy?: ScrapeStrategy;
  statusUrl?: String;
}

export interface StatusScrapeTargetWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  twitterHandle?: String;
  twitterHandle_not?: String;
  twitterHandle_in?: String[] | String;
  twitterHandle_not_in?: String[] | String;
  twitterHandle_lt?: String;
  twitterHandle_lte?: String;
  twitterHandle_gt?: String;
  twitterHandle_gte?: String;
  twitterHandle_contains?: String;
  twitterHandle_not_contains?: String;
  twitterHandle_starts_with?: String;
  twitterHandle_not_starts_with?: String;
  twitterHandle_ends_with?: String;
  twitterHandle_not_ends_with?: String;
  strategy?: ScrapeStrategy;
  strategy_not?: ScrapeStrategy;
  strategy_in?: ScrapeStrategy[] | ScrapeStrategy;
  strategy_not_in?: ScrapeStrategy[] | ScrapeStrategy;
  statusUrl?: String;
  statusUrl_not?: String;
  statusUrl_in?: String[] | String;
  statusUrl_not_in?: String[] | String;
  statusUrl_lt?: String;
  statusUrl_lte?: String;
  statusUrl_gt?: String;
  statusUrl_gte?: String;
  statusUrl_contains?: String;
  statusUrl_not_contains?: String;
  statusUrl_starts_with?: String;
  statusUrl_not_starts_with?: String;
  statusUrl_ends_with?: String;
  statusUrl_not_ends_with?: String;
  results_every?: StatusScrapeWhereInput;
  results_some?: StatusScrapeWhereInput;
  results_none?: StatusScrapeWhereInput;
  AND?: StatusScrapeTargetWhereInput[] | StatusScrapeTargetWhereInput;
  OR?: StatusScrapeTargetWhereInput[] | StatusScrapeTargetWhereInput;
  NOT?: StatusScrapeTargetWhereInput[] | StatusScrapeTargetWhereInput;
}

export interface StatusScrapeTargetUpsertWithoutResultsInput {
  update: StatusScrapeTargetUpdateWithoutResultsDataInput;
  create: StatusScrapeTargetCreateWithoutResultsInput;
}

export interface StatusScrapeWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  failed?: Boolean;
  failed_not?: Boolean;
  dom?: String;
  dom_not?: String;
  dom_in?: String[] | String;
  dom_not_in?: String[] | String;
  dom_lt?: String;
  dom_lte?: String;
  dom_gt?: String;
  dom_gte?: String;
  dom_contains?: String;
  dom_not_contains?: String;
  dom_starts_with?: String;
  dom_not_starts_with?: String;
  dom_ends_with?: String;
  dom_not_ends_with?: String;
  target?: StatusScrapeTargetWhereInput;
  results_every?: StatusScrapeResultWhereInput;
  results_some?: StatusScrapeResultWhereInput;
  results_none?: StatusScrapeResultWhereInput;
  AND?: StatusScrapeWhereInput[] | StatusScrapeWhereInput;
  OR?: StatusScrapeWhereInput[] | StatusScrapeWhereInput;
  NOT?: StatusScrapeWhereInput[] | StatusScrapeWhereInput;
}

export interface UserWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  email?: String;
  email_not?: String;
  email_in?: String[] | String;
  email_not_in?: String[] | String;
  email_lt?: String;
  email_lte?: String;
  email_gt?: String;
  email_gte?: String;
  email_contains?: String;
  email_not_contains?: String;
  email_starts_with?: String;
  email_not_starts_with?: String;
  email_ends_with?: String;
  email_not_ends_with?: String;
  password?: String;
  password_not?: String;
  password_in?: String[] | String;
  password_not_in?: String[] | String;
  password_lt?: String;
  password_lte?: String;
  password_gt?: String;
  password_gte?: String;
  password_contains?: String;
  password_not_contains?: String;
  password_starts_with?: String;
  password_not_starts_with?: String;
  password_ends_with?: String;
  password_not_ends_with?: String;
  AND?: UserWhereInput[] | UserWhereInput;
  OR?: UserWhereInput[] | UserWhereInput;
  NOT?: UserWhereInput[] | UserWhereInput;
}

export interface StatusScrapeResultCreateInput {
  scrape: StatusScrapeCreateOneWithoutResultsInput;
  category: String;
  component: String;
  status: SystemStatus;
}

export interface StatusScrapeTargetCreateInput {
  name: String;
  twitterHandle?: String;
  strategy?: ScrapeStrategy;
  statusUrl: String;
  results?: StatusScrapeCreateManyWithoutTargetInput;
}

export interface StatusScrapeResultUpdateManyWithoutScrapeInput {
  create?:
    | StatusScrapeResultCreateWithoutScrapeInput[]
    | StatusScrapeResultCreateWithoutScrapeInput;
}

export interface StatusScrapeUpsertWithoutResultsInput {
  update: StatusScrapeUpdateWithoutResultsDataInput;
  create: StatusScrapeCreateWithoutResultsInput;
}

export interface StatusScrapeTargetSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: StatusScrapeTargetWhereInput;
  AND?:
    | StatusScrapeTargetSubscriptionWhereInput[]
    | StatusScrapeTargetSubscriptionWhereInput;
  OR?:
    | StatusScrapeTargetSubscriptionWhereInput[]
    | StatusScrapeTargetSubscriptionWhereInput;
  NOT?:
    | StatusScrapeTargetSubscriptionWhereInput[]
    | StatusScrapeTargetSubscriptionWhereInput;
}

export interface StatusScrapeUpdateWithoutResultsDataInput {
  failed?: Boolean;
  dom?: String;
  target?: StatusScrapeTargetUpdateOneRequiredWithoutResultsInput;
}

export interface StatusScrapeSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: StatusScrapeWhereInput;
  AND?:
    | StatusScrapeSubscriptionWhereInput[]
    | StatusScrapeSubscriptionWhereInput;
  OR?:
    | StatusScrapeSubscriptionWhereInput[]
    | StatusScrapeSubscriptionWhereInput;
  NOT?:
    | StatusScrapeSubscriptionWhereInput[]
    | StatusScrapeSubscriptionWhereInput;
}

export interface StatusScrapeUpdateOneRequiredWithoutResultsInput {
  create?: StatusScrapeCreateWithoutResultsInput;
  update?: StatusScrapeUpdateWithoutResultsDataInput;
  upsert?: StatusScrapeUpsertWithoutResultsInput;
  connect?: StatusScrapeWhereUniqueInput;
}

export interface UserCreateInput {
  name: String;
  email: String;
  password: String;
}

export interface StatusScrapeUpdateWithoutTargetDataInput {
  failed?: Boolean;
  dom?: String;
  results?: StatusScrapeResultUpdateManyWithoutScrapeInput;
}

export interface StatusScrapeUpdateWithWhereUniqueWithoutTargetInput {
  where: StatusScrapeWhereUniqueInput;
  data: StatusScrapeUpdateWithoutTargetDataInput;
}

export interface StatusScrapeCreateInput {
  failed?: Boolean;
  dom?: String;
  target: StatusScrapeTargetCreateOneWithoutResultsInput;
  results?: StatusScrapeResultCreateManyWithoutScrapeInput;
}

export interface StatusScrapeTargetUpdateInput {
  name?: String;
  twitterHandle?: String;
  strategy?: ScrapeStrategy;
  statusUrl?: String;
  results?: StatusScrapeUpdateManyWithoutTargetInput;
}

export interface StatusScrapeTargetCreateOneWithoutResultsInput {
  create?: StatusScrapeTargetCreateWithoutResultsInput;
  connect?: StatusScrapeTargetWhereUniqueInput;
}

export type UserWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
  email?: String;
}>;

export interface StatusScrapeTargetCreateWithoutResultsInput {
  name: String;
  twitterHandle?: String;
  strategy?: ScrapeStrategy;
  statusUrl: String;
}

export interface UserSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: UserWhereInput;
  AND?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  OR?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  NOT?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
}

export interface StatusScrapeResultUpdateInput {
  scrape?: StatusScrapeUpdateOneRequiredWithoutResultsInput;
  category?: String;
  component?: String;
  status?: SystemStatus;
}

export interface UserUpdateInput {
  name?: String;
  email?: String;
  password?: String;
}

export interface StatusScrapeResultCreateWithoutScrapeInput {
  category: String;
  component: String;
  status: SystemStatus;
}

export type StatusScrapeTargetWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
  name?: String;
  twitterHandle?: String;
  statusUrl?: String;
}>;

export interface StatusScrapeUpdateInput {
  failed?: Boolean;
  dom?: String;
  target?: StatusScrapeTargetUpdateOneRequiredWithoutResultsInput;
  results?: StatusScrapeResultUpdateManyWithoutScrapeInput;
}

export interface StatusScrapeCreateWithoutTargetInput {
  failed?: Boolean;
  dom?: String;
  results?: StatusScrapeResultCreateManyWithoutScrapeInput;
}

export interface StatusScrapeCreateOneWithoutResultsInput {
  create?: StatusScrapeCreateWithoutResultsInput;
  connect?: StatusScrapeWhereUniqueInput;
}

export interface StatusScrapeCreateWithoutResultsInput {
  failed?: Boolean;
  dom?: String;
  target: StatusScrapeTargetCreateOneWithoutResultsInput;
}

export interface StatusScrapeResultWhereInput {
  scrape?: StatusScrapeWhereInput;
  category?: String;
  category_not?: String;
  category_in?: String[] | String;
  category_not_in?: String[] | String;
  category_lt?: String;
  category_lte?: String;
  category_gt?: String;
  category_gte?: String;
  category_contains?: String;
  category_not_contains?: String;
  category_starts_with?: String;
  category_not_starts_with?: String;
  category_ends_with?: String;
  category_not_ends_with?: String;
  component?: String;
  component_not?: String;
  component_in?: String[] | String;
  component_not_in?: String[] | String;
  component_lt?: String;
  component_lte?: String;
  component_gt?: String;
  component_gte?: String;
  component_contains?: String;
  component_not_contains?: String;
  component_starts_with?: String;
  component_not_starts_with?: String;
  component_ends_with?: String;
  component_not_ends_with?: String;
  status?: SystemStatus;
  status_not?: SystemStatus;
  status_in?: SystemStatus[] | SystemStatus;
  status_not_in?: SystemStatus[] | SystemStatus;
  AND?: StatusScrapeResultWhereInput[] | StatusScrapeResultWhereInput;
  OR?: StatusScrapeResultWhereInput[] | StatusScrapeResultWhereInput;
  NOT?: StatusScrapeResultWhereInput[] | StatusScrapeResultWhereInput;
}

export interface StatusScrapeTargetUpdateOneRequiredWithoutResultsInput {
  create?: StatusScrapeTargetCreateWithoutResultsInput;
  update?: StatusScrapeTargetUpdateWithoutResultsDataInput;
  upsert?: StatusScrapeTargetUpsertWithoutResultsInput;
  connect?: StatusScrapeTargetWhereUniqueInput;
}

export interface StatusScrapeCreateManyWithoutTargetInput {
  create?:
    | StatusScrapeCreateWithoutTargetInput[]
    | StatusScrapeCreateWithoutTargetInput;
  connect?: StatusScrapeWhereUniqueInput[] | StatusScrapeWhereUniqueInput;
}

export interface StatusScrapeUpdateManyWithoutTargetInput {
  create?:
    | StatusScrapeCreateWithoutTargetInput[]
    | StatusScrapeCreateWithoutTargetInput;
  delete?: StatusScrapeWhereUniqueInput[] | StatusScrapeWhereUniqueInput;
  connect?: StatusScrapeWhereUniqueInput[] | StatusScrapeWhereUniqueInput;
  disconnect?: StatusScrapeWhereUniqueInput[] | StatusScrapeWhereUniqueInput;
  update?:
    | StatusScrapeUpdateWithWhereUniqueWithoutTargetInput[]
    | StatusScrapeUpdateWithWhereUniqueWithoutTargetInput;
  upsert?:
    | StatusScrapeUpsertWithWhereUniqueWithoutTargetInput[]
    | StatusScrapeUpsertWithWhereUniqueWithoutTargetInput;
}

export interface StatusScrapeUpsertWithWhereUniqueWithoutTargetInput {
  where: StatusScrapeWhereUniqueInput;
  update: StatusScrapeUpdateWithoutTargetDataInput;
  create: StatusScrapeCreateWithoutTargetInput;
}

export interface StatusScrapeResultSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: StatusScrapeResultWhereInput;
  AND?:
    | StatusScrapeResultSubscriptionWhereInput[]
    | StatusScrapeResultSubscriptionWhereInput;
  OR?:
    | StatusScrapeResultSubscriptionWhereInput[]
    | StatusScrapeResultSubscriptionWhereInput;
  NOT?:
    | StatusScrapeResultSubscriptionWhereInput[]
    | StatusScrapeResultSubscriptionWhereInput;
}

export interface NodeNode {
  id: ID_Output;
}

export interface UserPreviousValuesNode {
  id: ID_Output;
  name: String;
  email: String;
  password: String;
}

export interface UserPreviousValues
  extends Promise<UserPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  email: () => Promise<String>;
  password: () => Promise<String>;
}

export interface UserPreviousValuesSubscription
  extends Promise<AsyncIterator<UserPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  email: () => Promise<AsyncIterator<String>>;
  password: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeTargetSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface StatusScrapeTargetSubscriptionPayload
  extends Promise<StatusScrapeTargetSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = StatusScrapeTarget>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = StatusScrapeTargetPreviousValues>() => T;
}

export interface StatusScrapeTargetSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = StatusScrapeTargetSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = StatusScrapeTargetPreviousValuesSubscription>() => T;
}

export interface StatusScrapeConnectionNode {}

export interface StatusScrapeConnection
  extends Promise<StatusScrapeConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = FragmentableArray<StatusScrapeEdgeNode>>() => T;
  aggregate: <T = AggregateStatusScrape>() => T;
}

export interface StatusScrapeConnectionSubscription
  extends Promise<AsyncIterator<StatusScrapeConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<StatusScrapeEdgeSubscription>>>() => T;
  aggregate: <T = AggregateStatusScrapeSubscription>() => T;
}

export interface AggregateStatusScrapeResultNode {
  count: Int;
}

export interface AggregateStatusScrapeResult
  extends Promise<AggregateStatusScrapeResultNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateStatusScrapeResultSubscription
  extends Promise<AsyncIterator<AggregateStatusScrapeResultNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface StatusScrapeResultEdgeNode {
  cursor: String;
}

export interface StatusScrapeResultEdge
  extends Promise<StatusScrapeResultEdgeNode>,
    Fragmentable {
  node: <T = StatusScrapeResult>() => T;
  cursor: () => Promise<String>;
}

export interface StatusScrapeResultEdgeSubscription
  extends Promise<AsyncIterator<StatusScrapeResultEdgeNode>>,
    Fragmentable {
  node: <T = StatusScrapeResultSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface BatchPayloadNode {
  count: Long;
}

export interface BatchPayload extends Promise<BatchPayloadNode>, Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayloadNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface StatusScrapeTargetNode {
  id: ID_Output;
  name: String;
  twitterHandle?: String;
  strategy: ScrapeStrategy;
  statusUrl: String;
}

export interface StatusScrapeTarget
  extends Promise<StatusScrapeTargetNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  twitterHandle: () => Promise<String>;
  strategy: () => Promise<ScrapeStrategy>;
  statusUrl: () => Promise<String>;
  results: <T = FragmentableArray<StatusScrapeNode>>(
    args?: {
      where?: StatusScrapeWhereInput;
      orderBy?: StatusScrapeOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface StatusScrapeTargetSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  twitterHandle: () => Promise<AsyncIterator<String>>;
  strategy: () => Promise<AsyncIterator<ScrapeStrategy>>;
  statusUrl: () => Promise<AsyncIterator<String>>;
  results: <T = Promise<AsyncIterator<StatusScrapeSubscription>>>(
    args?: {
      where?: StatusScrapeWhereInput;
      orderBy?: StatusScrapeOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface StatusScrapeResultConnectionNode {}

export interface StatusScrapeResultConnection
  extends Promise<StatusScrapeResultConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = FragmentableArray<StatusScrapeResultEdgeNode>>() => T;
  aggregate: <T = AggregateStatusScrapeResult>() => T;
}

export interface StatusScrapeResultConnectionSubscription
  extends Promise<AsyncIterator<StatusScrapeResultConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <
    T = Promise<AsyncIterator<StatusScrapeResultEdgeSubscription>>
  >() => T;
  aggregate: <T = AggregateStatusScrapeResultSubscription>() => T;
}

export interface AggregateUserNode {
  count: Int;
}

export interface AggregateUser
  extends Promise<AggregateUserNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateUserSubscription
  extends Promise<AsyncIterator<AggregateUserNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface AggregateStatusScrapeNode {
  count: Int;
}

export interface AggregateStatusScrape
  extends Promise<AggregateStatusScrapeNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateStatusScrapeSubscription
  extends Promise<AsyncIterator<AggregateStatusScrapeNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface UserConnectionNode {}

export interface UserConnection
  extends Promise<UserConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = FragmentableArray<UserEdgeNode>>() => T;
  aggregate: <T = AggregateUser>() => T;
}

export interface UserConnectionSubscription
  extends Promise<AsyncIterator<UserConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<UserEdgeSubscription>>>() => T;
  aggregate: <T = AggregateUserSubscription>() => T;
}

export interface StatusScrapeEdgeNode {
  cursor: String;
}

export interface StatusScrapeEdge
  extends Promise<StatusScrapeEdgeNode>,
    Fragmentable {
  node: <T = StatusScrape>() => T;
  cursor: () => Promise<String>;
}

export interface StatusScrapeEdgeSubscription
  extends Promise<AsyncIterator<StatusScrapeEdgeNode>>,
    Fragmentable {
  node: <T = StatusScrapeSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface UserNode {
  id: ID_Output;
  name: String;
  email: String;
  password: String;
}

export interface User extends Promise<UserNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  email: () => Promise<String>;
  password: () => Promise<String>;
}

export interface UserSubscription
  extends Promise<AsyncIterator<UserNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  email: () => Promise<AsyncIterator<String>>;
  password: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeNode {
  id: ID_Output;
  createdAt: DateTimeOutput;
  failed: Boolean;
  dom?: String;
}

export interface StatusScrape extends Promise<StatusScrapeNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  failed: () => Promise<Boolean>;
  dom: () => Promise<String>;
  target: <T = StatusScrapeTarget>() => T;
  results: <T = FragmentableArray<StatusScrapeResultNode>>(
    args?: {
      where?: StatusScrapeResultWhereInput;
      orderBy?: StatusScrapeResultOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface StatusScrapeSubscription
  extends Promise<AsyncIterator<StatusScrapeNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  failed: () => Promise<AsyncIterator<Boolean>>;
  dom: () => Promise<AsyncIterator<String>>;
  target: <T = StatusScrapeTargetSubscription>() => T;
  results: <T = Promise<AsyncIterator<StatusScrapeResultSubscription>>>(
    args?: {
      where?: StatusScrapeResultWhereInput;
      orderBy?: StatusScrapeResultOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface StatusScrapeTargetEdgeNode {
  cursor: String;
}

export interface StatusScrapeTargetEdge
  extends Promise<StatusScrapeTargetEdgeNode>,
    Fragmentable {
  node: <T = StatusScrapeTarget>() => T;
  cursor: () => Promise<String>;
}

export interface StatusScrapeTargetEdgeSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetEdgeNode>>,
    Fragmentable {
  node: <T = StatusScrapeTargetSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface StatusScrapeSubscriptionPayload
  extends Promise<StatusScrapeSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = StatusScrape>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = StatusScrapePreviousValues>() => T;
}

export interface StatusScrapeSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<StatusScrapeSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = StatusScrapeSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = StatusScrapePreviousValuesSubscription>() => T;
}

export interface UserSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface UserSubscriptionPayload
  extends Promise<UserSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = User>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = UserPreviousValues>() => T;
}

export interface UserSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = UserSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = UserPreviousValuesSubscription>() => T;
}

export interface UserEdgeNode {
  cursor: String;
}

export interface UserEdge extends Promise<UserEdgeNode>, Fragmentable {
  node: <T = User>() => T;
  cursor: () => Promise<String>;
}

export interface UserEdgeSubscription
  extends Promise<AsyncIterator<UserEdgeNode>>,
    Fragmentable {
  node: <T = UserSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeResultPreviousValuesNode {
  category: String;
  component: String;
  status: SystemStatus;
}

export interface StatusScrapeResultPreviousValues
  extends Promise<StatusScrapeResultPreviousValuesNode>,
    Fragmentable {
  category: () => Promise<String>;
  component: () => Promise<String>;
  status: () => Promise<SystemStatus>;
}

export interface StatusScrapeResultPreviousValuesSubscription
  extends Promise<AsyncIterator<StatusScrapeResultPreviousValuesNode>>,
    Fragmentable {
  category: () => Promise<AsyncIterator<String>>;
  component: () => Promise<AsyncIterator<String>>;
  status: () => Promise<AsyncIterator<SystemStatus>>;
}

export interface StatusScrapeResultSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface StatusScrapeResultSubscriptionPayload
  extends Promise<StatusScrapeResultSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = StatusScrapeResult>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = StatusScrapeResultPreviousValues>() => T;
}

export interface StatusScrapeResultSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<StatusScrapeResultSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = StatusScrapeResultSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = StatusScrapeResultPreviousValuesSubscription>() => T;
}

export interface PageInfoNode {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfo extends Promise<PageInfoNode>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfoNode>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapePreviousValuesNode {
  id: ID_Output;
  createdAt: DateTimeOutput;
  failed: Boolean;
  dom?: String;
}

export interface StatusScrapePreviousValues
  extends Promise<StatusScrapePreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  failed: () => Promise<Boolean>;
  dom: () => Promise<String>;
}

export interface StatusScrapePreviousValuesSubscription
  extends Promise<AsyncIterator<StatusScrapePreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  failed: () => Promise<AsyncIterator<Boolean>>;
  dom: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeTargetPreviousValuesNode {
  id: ID_Output;
  name: String;
  twitterHandle?: String;
  strategy: ScrapeStrategy;
  statusUrl: String;
}

export interface StatusScrapeTargetPreviousValues
  extends Promise<StatusScrapeTargetPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  twitterHandle: () => Promise<String>;
  strategy: () => Promise<ScrapeStrategy>;
  statusUrl: () => Promise<String>;
}

export interface StatusScrapeTargetPreviousValuesSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  twitterHandle: () => Promise<AsyncIterator<String>>;
  strategy: () => Promise<AsyncIterator<ScrapeStrategy>>;
  statusUrl: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeResultNode {
  category: String;
  component: String;
  status: SystemStatus;
}

export interface StatusScrapeResult
  extends Promise<StatusScrapeResultNode>,
    Fragmentable {
  scrape: <T = StatusScrape>() => T;
  category: () => Promise<String>;
  component: () => Promise<String>;
  status: () => Promise<SystemStatus>;
}

export interface StatusScrapeResultSubscription
  extends Promise<AsyncIterator<StatusScrapeResultNode>>,
    Fragmentable {
  scrape: <T = StatusScrapeSubscription>() => T;
  category: () => Promise<AsyncIterator<String>>;
  component: () => Promise<AsyncIterator<String>>;
  status: () => Promise<AsyncIterator<SystemStatus>>;
}

export interface StatusScrapeTargetConnectionNode {}

export interface StatusScrapeTargetConnection
  extends Promise<StatusScrapeTargetConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = FragmentableArray<StatusScrapeTargetEdgeNode>>() => T;
  aggregate: <T = AggregateStatusScrapeTarget>() => T;
}

export interface StatusScrapeTargetConnectionSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <
    T = Promise<AsyncIterator<StatusScrapeTargetEdgeSubscription>>
  >() => T;
  aggregate: <T = AggregateStatusScrapeTargetSubscription>() => T;
}

export interface AggregateStatusScrapeTargetNode {
  count: Int;
}

export interface AggregateStatusScrapeTarget
  extends Promise<AggregateStatusScrapeTargetNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateStatusScrapeTargetSubscription
  extends Promise<AsyncIterator<AggregateStatusScrapeTargetNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

export type Long = string;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
DateTime scalar input type, allowing Date
*/
export type DateTimeInput = Date | string;

/*
DateTime scalar output type, which is always a string
*/
export type DateTimeOutput = string;

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  endpoint: `https://us1.prisma.sh/peter-k/status-scrape/dev`
});
export const prisma = new Prisma();
