// Code generated by Prisma (prisma@1.18.0-beta.16). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode, GraphQLSchema } from "graphql";
import { IResolvers } from "graphql-tools/dist/Interfaces";
import { makePrismaClientClass, BaseClientOptions } from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export interface Exists {
  statusScrapeJob: (where?: StatusScrapeJobWhereInput) => Promise<boolean>;
  statusScrapeResult: (
    where?: StatusScrapeResultWhereInput
  ) => Promise<boolean>;
  statusScrapeTarget: (
    where?: StatusScrapeTargetWhereInput
  ) => Promise<boolean>;
  user: (where?: UserWhereInput) => Promise<boolean>;
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable;

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;
  $getAbstractResolvers(filterSchema?: GraphQLSchema | string): IResolvers;

  /**
   * Queries
   */

  statusScrapeJob: (where: StatusScrapeJobWhereUniqueInput) => StatusScrapeJob;
  statusScrapeJobs: (
    args?: {
      where?: StatusScrapeJobWhereInput;
      orderBy?: StatusScrapeJobOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<StatusScrapeJobNode>;
  statusScrapeJobsConnection: (
    args?: {
      where?: StatusScrapeJobWhereInput;
      orderBy?: StatusScrapeJobOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => StatusScrapeJobConnection;
  statusScrapeResult: (
    where: StatusScrapeResultWhereUniqueInput
  ) => StatusScrapeResult;
  statusScrapeResults: (
    args?: {
      where?: StatusScrapeResultWhereInput;
      orderBy?: StatusScrapeResultOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<StatusScrapeResultNode>;
  statusScrapeResultsConnection: (
    args?: {
      where?: StatusScrapeResultWhereInput;
      orderBy?: StatusScrapeResultOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => StatusScrapeResultConnection;
  statusScrapeTarget: (
    where: StatusScrapeTargetWhereUniqueInput
  ) => StatusScrapeTarget;
  statusScrapeTargets: (
    args?: {
      where?: StatusScrapeTargetWhereInput;
      orderBy?: StatusScrapeTargetOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<StatusScrapeTargetNode>;
  statusScrapeTargetsConnection: (
    args?: {
      where?: StatusScrapeTargetWhereInput;
      orderBy?: StatusScrapeTargetOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => StatusScrapeTargetConnection;
  user: (where: UserWhereUniqueInput) => User;
  users: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => FragmentableArray<UserNode>;
  usersConnection: (
    args?: {
      where?: UserWhereInput;
      orderBy?: UserOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => UserConnection;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createStatusScrapeJob: (data: StatusScrapeJobCreateInput) => StatusScrapeJob;
  updateStatusScrapeJob: (
    args: {
      data: StatusScrapeJobUpdateInput;
      where: StatusScrapeJobWhereUniqueInput;
    }
  ) => StatusScrapeJob;
  updateManyStatusScrapeJobs: (
    args: {
      data: StatusScrapeJobUpdateInput;
      where?: StatusScrapeJobWhereInput;
    }
  ) => BatchPayload;
  upsertStatusScrapeJob: (
    args: {
      where: StatusScrapeJobWhereUniqueInput;
      create: StatusScrapeJobCreateInput;
      update: StatusScrapeJobUpdateInput;
    }
  ) => StatusScrapeJob;
  deleteStatusScrapeJob: (
    where: StatusScrapeJobWhereUniqueInput
  ) => StatusScrapeJob;
  deleteManyStatusScrapeJobs: (
    where?: StatusScrapeJobWhereInput
  ) => BatchPayload;
  createStatusScrapeResult: (
    data: StatusScrapeResultCreateInput
  ) => StatusScrapeResult;
  updateStatusScrapeResult: (
    args: {
      data: StatusScrapeResultUpdateInput;
      where: StatusScrapeResultWhereUniqueInput;
    }
  ) => StatusScrapeResult;
  updateManyStatusScrapeResults: (
    args: {
      data: StatusScrapeResultUpdateInput;
      where?: StatusScrapeResultWhereInput;
    }
  ) => BatchPayload;
  upsertStatusScrapeResult: (
    args: {
      where: StatusScrapeResultWhereUniqueInput;
      create: StatusScrapeResultCreateInput;
      update: StatusScrapeResultUpdateInput;
    }
  ) => StatusScrapeResult;
  deleteStatusScrapeResult: (
    where: StatusScrapeResultWhereUniqueInput
  ) => StatusScrapeResult;
  deleteManyStatusScrapeResults: (
    where?: StatusScrapeResultWhereInput
  ) => BatchPayload;
  createStatusScrapeTarget: (
    data: StatusScrapeTargetCreateInput
  ) => StatusScrapeTarget;
  updateStatusScrapeTarget: (
    args: {
      data: StatusScrapeTargetUpdateInput;
      where: StatusScrapeTargetWhereUniqueInput;
    }
  ) => StatusScrapeTarget;
  updateManyStatusScrapeTargets: (
    args: {
      data: StatusScrapeTargetUpdateInput;
      where?: StatusScrapeTargetWhereInput;
    }
  ) => BatchPayload;
  upsertStatusScrapeTarget: (
    args: {
      where: StatusScrapeTargetWhereUniqueInput;
      create: StatusScrapeTargetCreateInput;
      update: StatusScrapeTargetUpdateInput;
    }
  ) => StatusScrapeTarget;
  deleteStatusScrapeTarget: (
    where: StatusScrapeTargetWhereUniqueInput
  ) => StatusScrapeTarget;
  deleteManyStatusScrapeTargets: (
    where?: StatusScrapeTargetWhereInput
  ) => BatchPayload;
  createUser: (data: UserCreateInput) => User;
  updateUser: (
    args: { data: UserUpdateInput; where: UserWhereUniqueInput }
  ) => User;
  updateManyUsers: (
    args: { data: UserUpdateInput; where?: UserWhereInput }
  ) => BatchPayload;
  upsertUser: (
    args: {
      where: UserWhereUniqueInput;
      create: UserCreateInput;
      update: UserUpdateInput;
    }
  ) => User;
  deleteUser: (where: UserWhereUniqueInput) => User;
  deleteManyUsers: (where?: UserWhereInput) => BatchPayload;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  statusScrapeJob: (
    where?: StatusScrapeJobSubscriptionWhereInput
  ) => StatusScrapeJobSubscriptionPayloadSubscription;
  statusScrapeResult: (
    where?: StatusScrapeResultSubscriptionWhereInput
  ) => StatusScrapeResultSubscriptionPayloadSubscription;
  statusScrapeTarget: (
    where?: StatusScrapeTargetSubscriptionWhereInput
  ) => StatusScrapeTargetSubscriptionPayloadSubscription;
  user: (
    where?: UserSubscriptionWhereInput
  ) => UserSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type SystemStatus = "OPERATIONAL" | "UNKNOWN";

export type ScrapeJobStatus =
  | "SCHEDULED"
  | "RUNNING"
  | "DONE"
  | "FAILED"
  | "TIMED_OUT";

export type StatusScrapeJobOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC"
  | "dom_ASC"
  | "dom_DESC"
  | "status_ASC"
  | "status_DESC";

export type ScrapeStrategy = "STATUSPAGE_IO";

export type StatusScrapeResultOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "category_ASC"
  | "category_DESC"
  | "component_ASC"
  | "component_DESC"
  | "status_ASC"
  | "status_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type StatusScrapeTargetOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "statusUrl_ASC"
  | "statusUrl_DESC"
  | "companyUrl_ASC"
  | "companyUrl_DESC"
  | "strategy_ASC"
  | "strategy_DESC"
  | "twitterHandle_ASC"
  | "twitterHandle_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type UserOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "name_ASC"
  | "name_DESC"
  | "email_ASC"
  | "email_DESC"
  | "password_ASC"
  | "password_DESC"
  | "createdAt_ASC"
  | "createdAt_DESC"
  | "updatedAt_ASC"
  | "updatedAt_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export interface StatusScrapeResultCreateManyWithoutScrapeInput {
  create?:
    | StatusScrapeResultCreateWithoutScrapeInput[]
    | StatusScrapeResultCreateWithoutScrapeInput;
  connect?:
    | StatusScrapeResultWhereUniqueInput[]
    | StatusScrapeResultWhereUniqueInput;
}

export type StatusScrapeJobWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface StatusScrapeTargetUpsertWithoutResultsInput {
  update: StatusScrapeTargetUpdateWithoutResultsDataInput;
  create: StatusScrapeTargetCreateWithoutResultsInput;
}

export interface StatusScrapeResultWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  scrape?: StatusScrapeJobWhereInput;
  category?: String;
  category_not?: String;
  category_in?: String[] | String;
  category_not_in?: String[] | String;
  category_lt?: String;
  category_lte?: String;
  category_gt?: String;
  category_gte?: String;
  category_contains?: String;
  category_not_contains?: String;
  category_starts_with?: String;
  category_not_starts_with?: String;
  category_ends_with?: String;
  category_not_ends_with?: String;
  component?: String;
  component_not?: String;
  component_in?: String[] | String;
  component_not_in?: String[] | String;
  component_lt?: String;
  component_lte?: String;
  component_gt?: String;
  component_gte?: String;
  component_contains?: String;
  component_not_contains?: String;
  component_starts_with?: String;
  component_not_starts_with?: String;
  component_ends_with?: String;
  component_not_ends_with?: String;
  status?: SystemStatus;
  status_not?: SystemStatus;
  status_in?: SystemStatus[] | SystemStatus;
  status_not_in?: SystemStatus[] | SystemStatus;
  AND?: StatusScrapeResultWhereInput[] | StatusScrapeResultWhereInput;
  OR?: StatusScrapeResultWhereInput[] | StatusScrapeResultWhereInput;
  NOT?: StatusScrapeResultWhereInput[] | StatusScrapeResultWhereInput;
}

export interface StatusScrapeResultUpdateManyWithoutScrapeInput {
  create?:
    | StatusScrapeResultCreateWithoutScrapeInput[]
    | StatusScrapeResultCreateWithoutScrapeInput;
  delete?:
    | StatusScrapeResultWhereUniqueInput[]
    | StatusScrapeResultWhereUniqueInput;
  connect?:
    | StatusScrapeResultWhereUniqueInput[]
    | StatusScrapeResultWhereUniqueInput;
  disconnect?:
    | StatusScrapeResultWhereUniqueInput[]
    | StatusScrapeResultWhereUniqueInput;
  update?:
    | StatusScrapeResultUpdateWithWhereUniqueWithoutScrapeInput[]
    | StatusScrapeResultUpdateWithWhereUniqueWithoutScrapeInput;
  upsert?:
    | StatusScrapeResultUpsertWithWhereUniqueWithoutScrapeInput[]
    | StatusScrapeResultUpsertWithWhereUniqueWithoutScrapeInput;
}

export interface StatusScrapeJobWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  createdAt?: DateTimeInput;
  createdAt_not?: DateTimeInput;
  createdAt_in?: DateTimeInput[] | DateTimeInput;
  createdAt_not_in?: DateTimeInput[] | DateTimeInput;
  createdAt_lt?: DateTimeInput;
  createdAt_lte?: DateTimeInput;
  createdAt_gt?: DateTimeInput;
  createdAt_gte?: DateTimeInput;
  updatedAt?: DateTimeInput;
  updatedAt_not?: DateTimeInput;
  updatedAt_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput;
  updatedAt_lt?: DateTimeInput;
  updatedAt_lte?: DateTimeInput;
  updatedAt_gt?: DateTimeInput;
  updatedAt_gte?: DateTimeInput;
  dom?: String;
  dom_not?: String;
  dom_in?: String[] | String;
  dom_not_in?: String[] | String;
  dom_lt?: String;
  dom_lte?: String;
  dom_gt?: String;
  dom_gte?: String;
  dom_contains?: String;
  dom_not_contains?: String;
  dom_starts_with?: String;
  dom_not_starts_with?: String;
  dom_ends_with?: String;
  dom_not_ends_with?: String;
  target?: StatusScrapeTargetWhereInput;
  results_every?: StatusScrapeResultWhereInput;
  results_some?: StatusScrapeResultWhereInput;
  results_none?: StatusScrapeResultWhereInput;
  status?: ScrapeJobStatus;
  status_not?: ScrapeJobStatus;
  status_in?: ScrapeJobStatus[] | ScrapeJobStatus;
  status_not_in?: ScrapeJobStatus[] | ScrapeJobStatus;
  AND?: StatusScrapeJobWhereInput[] | StatusScrapeJobWhereInput;
  OR?: StatusScrapeJobWhereInput[] | StatusScrapeJobWhereInput;
  NOT?: StatusScrapeJobWhereInput[] | StatusScrapeJobWhereInput;
}

export interface StatusScrapeTargetCreateInput {
  name: String;
  statusUrl: String;
  companyUrl: String;
  strategy?: ScrapeStrategy;
  twitterHandle?: String;
  results?: StatusScrapeJobCreateManyWithoutTargetInput;
}

export interface StatusScrapeResultCreateInput {
  scrape: StatusScrapeJobCreateOneWithoutResultsInput;
  category: String;
  component: String;
  status: SystemStatus;
}

export interface StatusScrapeJobUpsertWithoutResultsInput {
  update: StatusScrapeJobUpdateWithoutResultsDataInput;
  create: StatusScrapeJobCreateWithoutResultsInput;
}

export interface StatusScrapeResultUpdateWithWhereUniqueWithoutScrapeInput {
  where: StatusScrapeResultWhereUniqueInput;
  data: StatusScrapeResultUpdateWithoutScrapeDataInput;
}

export interface StatusScrapeJobUpdateWithoutResultsDataInput {
  dom?: String;
  target?: StatusScrapeTargetUpdateOneRequiredWithoutResultsInput;
  status?: ScrapeJobStatus;
}

export interface StatusScrapeTargetSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: StatusScrapeTargetWhereInput;
  AND?:
    | StatusScrapeTargetSubscriptionWhereInput[]
    | StatusScrapeTargetSubscriptionWhereInput;
  OR?:
    | StatusScrapeTargetSubscriptionWhereInput[]
    | StatusScrapeTargetSubscriptionWhereInput;
  NOT?:
    | StatusScrapeTargetSubscriptionWhereInput[]
    | StatusScrapeTargetSubscriptionWhereInput;
}

export interface StatusScrapeJobUpdateOneRequiredWithoutResultsInput {
  create?: StatusScrapeJobCreateWithoutResultsInput;
  update?: StatusScrapeJobUpdateWithoutResultsDataInput;
  upsert?: StatusScrapeJobUpsertWithoutResultsInput;
  connect?: StatusScrapeJobWhereUniqueInput;
}

export interface StatusScrapeJobSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: StatusScrapeJobWhereInput;
  AND?:
    | StatusScrapeJobSubscriptionWhereInput[]
    | StatusScrapeJobSubscriptionWhereInput;
  OR?:
    | StatusScrapeJobSubscriptionWhereInput[]
    | StatusScrapeJobSubscriptionWhereInput;
  NOT?:
    | StatusScrapeJobSubscriptionWhereInput[]
    | StatusScrapeJobSubscriptionWhereInput;
}

export type StatusScrapeResultWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
}>;

export interface StatusScrapeJobUpsertWithWhereUniqueWithoutTargetInput {
  where: StatusScrapeJobWhereUniqueInput;
  update: StatusScrapeJobUpdateWithoutTargetDataInput;
  create: StatusScrapeJobCreateWithoutTargetInput;
}

export interface StatusScrapeJobCreateInput {
  dom?: String;
  target: StatusScrapeTargetCreateOneWithoutResultsInput;
  results?: StatusScrapeResultCreateManyWithoutScrapeInput;
  status: ScrapeJobStatus;
}

export type StatusScrapeTargetWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
  name?: String;
  statusUrl?: String;
  companyUrl?: String;
  twitterHandle?: String;
}>;

export interface StatusScrapeTargetCreateOneWithoutResultsInput {
  create?: StatusScrapeTargetCreateWithoutResultsInput;
  connect?: StatusScrapeTargetWhereUniqueInput;
}

export interface StatusScrapeJobUpdateManyWithoutTargetInput {
  create?:
    | StatusScrapeJobCreateWithoutTargetInput[]
    | StatusScrapeJobCreateWithoutTargetInput;
  delete?: StatusScrapeJobWhereUniqueInput[] | StatusScrapeJobWhereUniqueInput;
  connect?: StatusScrapeJobWhereUniqueInput[] | StatusScrapeJobWhereUniqueInput;
  disconnect?:
    | StatusScrapeJobWhereUniqueInput[]
    | StatusScrapeJobWhereUniqueInput;
  update?:
    | StatusScrapeJobUpdateWithWhereUniqueWithoutTargetInput[]
    | StatusScrapeJobUpdateWithWhereUniqueWithoutTargetInput;
  upsert?:
    | StatusScrapeJobUpsertWithWhereUniqueWithoutTargetInput[]
    | StatusScrapeJobUpsertWithWhereUniqueWithoutTargetInput;
}

export interface StatusScrapeTargetCreateWithoutResultsInput {
  name: String;
  statusUrl: String;
  companyUrl: String;
  strategy?: ScrapeStrategy;
  twitterHandle?: String;
}

export interface StatusScrapeJobCreateWithoutTargetInput {
  dom?: String;
  results?: StatusScrapeResultCreateManyWithoutScrapeInput;
  status: ScrapeJobStatus;
}

export interface StatusScrapeResultUpdateInput {
  scrape?: StatusScrapeJobUpdateOneRequiredWithoutResultsInput;
  category?: String;
  component?: String;
  status?: SystemStatus;
}

export interface StatusScrapeJobCreateManyWithoutTargetInput {
  create?:
    | StatusScrapeJobCreateWithoutTargetInput[]
    | StatusScrapeJobCreateWithoutTargetInput;
  connect?: StatusScrapeJobWhereUniqueInput[] | StatusScrapeJobWhereUniqueInput;
}

export interface StatusScrapeResultCreateWithoutScrapeInput {
  category: String;
  component: String;
  status: SystemStatus;
}

export interface UserSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: UserWhereInput;
  AND?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  OR?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
  NOT?: UserSubscriptionWhereInput[] | UserSubscriptionWhereInput;
}

export interface StatusScrapeJobUpdateInput {
  dom?: String;
  target?: StatusScrapeTargetUpdateOneRequiredWithoutResultsInput;
  results?: StatusScrapeResultUpdateManyWithoutScrapeInput;
  status?: ScrapeJobStatus;
}

export interface UserUpdateInput {
  name?: String;
  email?: String;
  password?: String;
}

export interface StatusScrapeTargetUpdateOneRequiredWithoutResultsInput {
  create?: StatusScrapeTargetCreateWithoutResultsInput;
  update?: StatusScrapeTargetUpdateWithoutResultsDataInput;
  upsert?: StatusScrapeTargetUpsertWithoutResultsInput;
  connect?: StatusScrapeTargetWhereUniqueInput;
}

export interface StatusScrapeJobUpdateWithoutTargetDataInput {
  dom?: String;
  results?: StatusScrapeResultUpdateManyWithoutScrapeInput;
  status?: ScrapeJobStatus;
}

export interface StatusScrapeTargetUpdateWithoutResultsDataInput {
  name?: String;
  statusUrl?: String;
  companyUrl?: String;
  strategy?: ScrapeStrategy;
  twitterHandle?: String;
}

export interface StatusScrapeTargetUpdateInput {
  name?: String;
  statusUrl?: String;
  companyUrl?: String;
  strategy?: ScrapeStrategy;
  twitterHandle?: String;
  results?: StatusScrapeJobUpdateManyWithoutTargetInput;
}

export interface StatusScrapeTargetWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  statusUrl?: String;
  statusUrl_not?: String;
  statusUrl_in?: String[] | String;
  statusUrl_not_in?: String[] | String;
  statusUrl_lt?: String;
  statusUrl_lte?: String;
  statusUrl_gt?: String;
  statusUrl_gte?: String;
  statusUrl_contains?: String;
  statusUrl_not_contains?: String;
  statusUrl_starts_with?: String;
  statusUrl_not_starts_with?: String;
  statusUrl_ends_with?: String;
  statusUrl_not_ends_with?: String;
  companyUrl?: String;
  companyUrl_not?: String;
  companyUrl_in?: String[] | String;
  companyUrl_not_in?: String[] | String;
  companyUrl_lt?: String;
  companyUrl_lte?: String;
  companyUrl_gt?: String;
  companyUrl_gte?: String;
  companyUrl_contains?: String;
  companyUrl_not_contains?: String;
  companyUrl_starts_with?: String;
  companyUrl_not_starts_with?: String;
  companyUrl_ends_with?: String;
  companyUrl_not_ends_with?: String;
  strategy?: ScrapeStrategy;
  strategy_not?: ScrapeStrategy;
  strategy_in?: ScrapeStrategy[] | ScrapeStrategy;
  strategy_not_in?: ScrapeStrategy[] | ScrapeStrategy;
  twitterHandle?: String;
  twitterHandle_not?: String;
  twitterHandle_in?: String[] | String;
  twitterHandle_not_in?: String[] | String;
  twitterHandle_lt?: String;
  twitterHandle_lte?: String;
  twitterHandle_gt?: String;
  twitterHandle_gte?: String;
  twitterHandle_contains?: String;
  twitterHandle_not_contains?: String;
  twitterHandle_starts_with?: String;
  twitterHandle_not_starts_with?: String;
  twitterHandle_ends_with?: String;
  twitterHandle_not_ends_with?: String;
  results_every?: StatusScrapeJobWhereInput;
  results_some?: StatusScrapeJobWhereInput;
  results_none?: StatusScrapeJobWhereInput;
  AND?: StatusScrapeTargetWhereInput[] | StatusScrapeTargetWhereInput;
  OR?: StatusScrapeTargetWhereInput[] | StatusScrapeTargetWhereInput;
  NOT?: StatusScrapeTargetWhereInput[] | StatusScrapeTargetWhereInput;
}

export interface UserWhereInput {
  id?: ID_Input;
  id_not?: ID_Input;
  id_in?: ID_Input[] | ID_Input;
  id_not_in?: ID_Input[] | ID_Input;
  id_lt?: ID_Input;
  id_lte?: ID_Input;
  id_gt?: ID_Input;
  id_gte?: ID_Input;
  id_contains?: ID_Input;
  id_not_contains?: ID_Input;
  id_starts_with?: ID_Input;
  id_not_starts_with?: ID_Input;
  id_ends_with?: ID_Input;
  id_not_ends_with?: ID_Input;
  name?: String;
  name_not?: String;
  name_in?: String[] | String;
  name_not_in?: String[] | String;
  name_lt?: String;
  name_lte?: String;
  name_gt?: String;
  name_gte?: String;
  name_contains?: String;
  name_not_contains?: String;
  name_starts_with?: String;
  name_not_starts_with?: String;
  name_ends_with?: String;
  name_not_ends_with?: String;
  email?: String;
  email_not?: String;
  email_in?: String[] | String;
  email_not_in?: String[] | String;
  email_lt?: String;
  email_lte?: String;
  email_gt?: String;
  email_gte?: String;
  email_contains?: String;
  email_not_contains?: String;
  email_starts_with?: String;
  email_not_starts_with?: String;
  email_ends_with?: String;
  email_not_ends_with?: String;
  password?: String;
  password_not?: String;
  password_in?: String[] | String;
  password_not_in?: String[] | String;
  password_lt?: String;
  password_lte?: String;
  password_gt?: String;
  password_gte?: String;
  password_contains?: String;
  password_not_contains?: String;
  password_starts_with?: String;
  password_not_starts_with?: String;
  password_ends_with?: String;
  password_not_ends_with?: String;
  AND?: UserWhereInput[] | UserWhereInput;
  OR?: UserWhereInput[] | UserWhereInput;
  NOT?: UserWhereInput[] | UserWhereInput;
}

export interface StatusScrapeResultUpsertWithWhereUniqueWithoutScrapeInput {
  where: StatusScrapeResultWhereUniqueInput;
  update: StatusScrapeResultUpdateWithoutScrapeDataInput;
  create: StatusScrapeResultCreateWithoutScrapeInput;
}

export interface StatusScrapeResultUpdateWithoutScrapeDataInput {
  category?: String;
  component?: String;
  status?: SystemStatus;
}

export interface StatusScrapeJobCreateOneWithoutResultsInput {
  create?: StatusScrapeJobCreateWithoutResultsInput;
  connect?: StatusScrapeJobWhereUniqueInput;
}

export interface StatusScrapeJobCreateWithoutResultsInput {
  dom?: String;
  target: StatusScrapeTargetCreateOneWithoutResultsInput;
  status: ScrapeJobStatus;
}

export interface StatusScrapeResultSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType;
  updatedFields_contains?: String;
  updatedFields_contains_every?: String[] | String;
  updatedFields_contains_some?: String[] | String;
  node?: StatusScrapeResultWhereInput;
  AND?:
    | StatusScrapeResultSubscriptionWhereInput[]
    | StatusScrapeResultSubscriptionWhereInput;
  OR?:
    | StatusScrapeResultSubscriptionWhereInput[]
    | StatusScrapeResultSubscriptionWhereInput;
  NOT?:
    | StatusScrapeResultSubscriptionWhereInput[]
    | StatusScrapeResultSubscriptionWhereInput;
}

export type UserWhereUniqueInput = AtLeastOne<{
  id: ID_Input;
  email?: String;
}>;

export interface StatusScrapeJobUpdateWithWhereUniqueWithoutTargetInput {
  where: StatusScrapeJobWhereUniqueInput;
  data: StatusScrapeJobUpdateWithoutTargetDataInput;
}

export interface UserCreateInput {
  name: String;
  email: String;
  password: String;
}

export interface NodeNode {
  id: ID_Output;
}

export interface UserPreviousValuesNode {
  id: ID_Output;
  name: String;
  email: String;
  password: String;
}

export interface UserPreviousValues
  extends Promise<UserPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  email: () => Promise<String>;
  password: () => Promise<String>;
}

export interface UserPreviousValuesSubscription
  extends Promise<AsyncIterator<UserPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  email: () => Promise<AsyncIterator<String>>;
  password: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeResultEdgeNode {
  cursor: String;
}

export interface StatusScrapeResultEdge
  extends Promise<StatusScrapeResultEdgeNode>,
    Fragmentable {
  node: <T = StatusScrapeResult>() => T;
  cursor: () => Promise<String>;
}

export interface StatusScrapeResultEdgeSubscription
  extends Promise<AsyncIterator<StatusScrapeResultEdgeNode>>,
    Fragmentable {
  node: <T = StatusScrapeResultSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeTargetNode {
  id: ID_Output;
  name: String;
  statusUrl: String;
  companyUrl: String;
  strategy: ScrapeStrategy;
  twitterHandle?: String;
}

export interface StatusScrapeTarget
  extends Promise<StatusScrapeTargetNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  statusUrl: () => Promise<String>;
  companyUrl: () => Promise<String>;
  strategy: () => Promise<ScrapeStrategy>;
  twitterHandle: () => Promise<String>;
  results: <T = FragmentableArray<StatusScrapeJobNode>>(
    args?: {
      where?: StatusScrapeJobWhereInput;
      orderBy?: StatusScrapeJobOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface StatusScrapeTargetSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  statusUrl: () => Promise<AsyncIterator<String>>;
  companyUrl: () => Promise<AsyncIterator<String>>;
  strategy: () => Promise<AsyncIterator<ScrapeStrategy>>;
  twitterHandle: () => Promise<AsyncIterator<String>>;
  results: <T = Promise<AsyncIterator<StatusScrapeJobSubscription>>>(
    args?: {
      where?: StatusScrapeJobWhereInput;
      orderBy?: StatusScrapeJobOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
}

export interface StatusScrapeResultConnectionNode {}

export interface StatusScrapeResultConnection
  extends Promise<StatusScrapeResultConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = FragmentableArray<StatusScrapeResultEdgeNode>>() => T;
  aggregate: <T = AggregateStatusScrapeResult>() => T;
}

export interface StatusScrapeResultConnectionSubscription
  extends Promise<AsyncIterator<StatusScrapeResultConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <
    T = Promise<AsyncIterator<StatusScrapeResultEdgeSubscription>>
  >() => T;
  aggregate: <T = AggregateStatusScrapeResultSubscription>() => T;
}

export interface StatusScrapeResultNode {
  id: ID_Output;
  category: String;
  component: String;
  status: SystemStatus;
}

export interface StatusScrapeResult
  extends Promise<StatusScrapeResultNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  scrape: <T = StatusScrapeJob>() => T;
  category: () => Promise<String>;
  component: () => Promise<String>;
  status: () => Promise<SystemStatus>;
}

export interface StatusScrapeResultSubscription
  extends Promise<AsyncIterator<StatusScrapeResultNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  scrape: <T = StatusScrapeJobSubscription>() => T;
  category: () => Promise<AsyncIterator<String>>;
  component: () => Promise<AsyncIterator<String>>;
  status: () => Promise<AsyncIterator<SystemStatus>>;
}

export interface BatchPayloadNode {
  count: Long;
}

export interface BatchPayload extends Promise<BatchPayloadNode>, Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayloadNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface PageInfoNode {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfo extends Promise<PageInfoNode>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfoNode>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeTargetPreviousValuesNode {
  id: ID_Output;
  name: String;
  statusUrl: String;
  companyUrl: String;
  strategy: ScrapeStrategy;
  twitterHandle?: String;
}

export interface StatusScrapeTargetPreviousValues
  extends Promise<StatusScrapeTargetPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  statusUrl: () => Promise<String>;
  companyUrl: () => Promise<String>;
  strategy: () => Promise<ScrapeStrategy>;
  twitterHandle: () => Promise<String>;
}

export interface StatusScrapeTargetPreviousValuesSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  statusUrl: () => Promise<AsyncIterator<String>>;
  companyUrl: () => Promise<AsyncIterator<String>>;
  strategy: () => Promise<AsyncIterator<ScrapeStrategy>>;
  twitterHandle: () => Promise<AsyncIterator<String>>;
}

export interface AggregateStatusScrapeJobNode {
  count: Int;
}

export interface AggregateStatusScrapeJob
  extends Promise<AggregateStatusScrapeJobNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateStatusScrapeJobSubscription
  extends Promise<AsyncIterator<AggregateStatusScrapeJobNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface AggregateUserNode {
  count: Int;
}

export interface AggregateUser
  extends Promise<AggregateUserNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateUserSubscription
  extends Promise<AsyncIterator<AggregateUserNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface UserConnectionNode {}

export interface UserConnection
  extends Promise<UserConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = FragmentableArray<UserEdgeNode>>() => T;
  aggregate: <T = AggregateUser>() => T;
}

export interface UserConnectionSubscription
  extends Promise<AsyncIterator<UserConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<UserEdgeSubscription>>>() => T;
  aggregate: <T = AggregateUserSubscription>() => T;
}

export interface StatusScrapeJobEdgeNode {
  cursor: String;
}

export interface StatusScrapeJobEdge
  extends Promise<StatusScrapeJobEdgeNode>,
    Fragmentable {
  node: <T = StatusScrapeJob>() => T;
  cursor: () => Promise<String>;
}

export interface StatusScrapeJobEdgeSubscription
  extends Promise<AsyncIterator<StatusScrapeJobEdgeNode>>,
    Fragmentable {
  node: <T = StatusScrapeJobSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface UserNode {
  id: ID_Output;
  name: String;
  email: String;
  password: String;
}

export interface User extends Promise<UserNode>, Fragmentable {
  id: () => Promise<ID_Output>;
  name: () => Promise<String>;
  email: () => Promise<String>;
  password: () => Promise<String>;
}

export interface UserSubscription
  extends Promise<AsyncIterator<UserNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  name: () => Promise<AsyncIterator<String>>;
  email: () => Promise<AsyncIterator<String>>;
  password: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeJobNode {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  dom?: String;
  status: ScrapeJobStatus;
}

export interface StatusScrapeJob
  extends Promise<StatusScrapeJobNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  dom: () => Promise<String>;
  target: <T = StatusScrapeTarget>() => T;
  results: <T = FragmentableArray<StatusScrapeResultNode>>(
    args?: {
      where?: StatusScrapeResultWhereInput;
      orderBy?: StatusScrapeResultOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
  status: () => Promise<ScrapeJobStatus>;
}

export interface StatusScrapeJobSubscription
  extends Promise<AsyncIterator<StatusScrapeJobNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  dom: () => Promise<AsyncIterator<String>>;
  target: <T = StatusScrapeTargetSubscription>() => T;
  results: <T = Promise<AsyncIterator<StatusScrapeResultSubscription>>>(
    args?: {
      where?: StatusScrapeResultWhereInput;
      orderBy?: StatusScrapeResultOrderByInput;
      skip?: Int;
      after?: String;
      before?: String;
      first?: Int;
      last?: Int;
    }
  ) => T;
  status: () => Promise<AsyncIterator<ScrapeJobStatus>>;
}

export interface StatusScrapeTargetEdgeNode {
  cursor: String;
}

export interface StatusScrapeTargetEdge
  extends Promise<StatusScrapeTargetEdgeNode>,
    Fragmentable {
  node: <T = StatusScrapeTarget>() => T;
  cursor: () => Promise<String>;
}

export interface StatusScrapeTargetEdgeSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetEdgeNode>>,
    Fragmentable {
  node: <T = StatusScrapeTargetSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeJobSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface StatusScrapeJobSubscriptionPayload
  extends Promise<StatusScrapeJobSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = StatusScrapeJob>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = StatusScrapeJobPreviousValues>() => T;
}

export interface StatusScrapeJobSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<StatusScrapeJobSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = StatusScrapeJobSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = StatusScrapeJobPreviousValuesSubscription>() => T;
}

export interface StatusScrapeJobConnectionNode {}

export interface StatusScrapeJobConnection
  extends Promise<StatusScrapeJobConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = FragmentableArray<StatusScrapeJobEdgeNode>>() => T;
  aggregate: <T = AggregateStatusScrapeJob>() => T;
}

export interface StatusScrapeJobConnectionSubscription
  extends Promise<AsyncIterator<StatusScrapeJobConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<StatusScrapeJobEdgeSubscription>>>() => T;
  aggregate: <T = AggregateStatusScrapeJobSubscription>() => T;
}

export interface UserEdgeNode {
  cursor: String;
}

export interface UserEdge extends Promise<UserEdgeNode>, Fragmentable {
  node: <T = User>() => T;
  cursor: () => Promise<String>;
}

export interface UserEdgeSubscription
  extends Promise<AsyncIterator<UserEdgeNode>>,
    Fragmentable {
  node: <T = UserSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface StatusScrapeResultPreviousValuesNode {
  id: ID_Output;
  category: String;
  component: String;
  status: SystemStatus;
}

export interface StatusScrapeResultPreviousValues
  extends Promise<StatusScrapeResultPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  category: () => Promise<String>;
  component: () => Promise<String>;
  status: () => Promise<SystemStatus>;
}

export interface StatusScrapeResultPreviousValuesSubscription
  extends Promise<AsyncIterator<StatusScrapeResultPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  category: () => Promise<AsyncIterator<String>>;
  component: () => Promise<AsyncIterator<String>>;
  status: () => Promise<AsyncIterator<SystemStatus>>;
}

export interface StatusScrapeResultSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface StatusScrapeResultSubscriptionPayload
  extends Promise<StatusScrapeResultSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = StatusScrapeResult>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = StatusScrapeResultPreviousValues>() => T;
}

export interface StatusScrapeResultSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<StatusScrapeResultSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = StatusScrapeResultSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = StatusScrapeResultPreviousValuesSubscription>() => T;
}

export interface StatusScrapeTargetSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface StatusScrapeTargetSubscriptionPayload
  extends Promise<StatusScrapeTargetSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = StatusScrapeTarget>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = StatusScrapeTargetPreviousValues>() => T;
}

export interface StatusScrapeTargetSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = StatusScrapeTargetSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = StatusScrapeTargetPreviousValuesSubscription>() => T;
}

export interface StatusScrapeJobPreviousValuesNode {
  id: ID_Output;
  createdAt: DateTimeOutput;
  updatedAt: DateTimeOutput;
  dom?: String;
  status: ScrapeJobStatus;
}

export interface StatusScrapeJobPreviousValues
  extends Promise<StatusScrapeJobPreviousValuesNode>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  createdAt: () => Promise<DateTimeOutput>;
  updatedAt: () => Promise<DateTimeOutput>;
  dom: () => Promise<String>;
  status: () => Promise<ScrapeJobStatus>;
}

export interface StatusScrapeJobPreviousValuesSubscription
  extends Promise<AsyncIterator<StatusScrapeJobPreviousValuesNode>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>;
  dom: () => Promise<AsyncIterator<String>>;
  status: () => Promise<AsyncIterator<ScrapeJobStatus>>;
}

export interface UserSubscriptionPayloadNode {
  mutation: MutationType;
  updatedFields?: String[];
}

export interface UserSubscriptionPayload
  extends Promise<UserSubscriptionPayloadNode>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = User>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = UserPreviousValues>() => T;
}

export interface UserSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserSubscriptionPayloadNode>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = UserSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = UserPreviousValuesSubscription>() => T;
}

export interface AggregateStatusScrapeResultNode {
  count: Int;
}

export interface AggregateStatusScrapeResult
  extends Promise<AggregateStatusScrapeResultNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateStatusScrapeResultSubscription
  extends Promise<AsyncIterator<AggregateStatusScrapeResultNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface StatusScrapeTargetConnectionNode {}

export interface StatusScrapeTargetConnection
  extends Promise<StatusScrapeTargetConnectionNode>,
    Fragmentable {
  pageInfo: <T = PageInfo>() => T;
  edges: <T = FragmentableArray<StatusScrapeTargetEdgeNode>>() => T;
  aggregate: <T = AggregateStatusScrapeTarget>() => T;
}

export interface StatusScrapeTargetConnectionSubscription
  extends Promise<AsyncIterator<StatusScrapeTargetConnectionNode>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <
    T = Promise<AsyncIterator<StatusScrapeTargetEdgeSubscription>>
  >() => T;
  aggregate: <T = AggregateStatusScrapeTargetSubscription>() => T;
}

export interface AggregateStatusScrapeTargetNode {
  count: Int;
}

export interface AggregateStatusScrapeTarget
  extends Promise<AggregateStatusScrapeTargetNode>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateStatusScrapeTargetSubscription
  extends Promise<AsyncIterator<AggregateStatusScrapeTargetNode>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export type Long = string;

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
DateTime scalar input type, allowing Date
*/
export type DateTimeInput = Date | string;

/*
DateTime scalar output type, which is always a string
*/
export type DateTimeOutput = string;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number;

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  endpoint: `https://us1.prisma.sh/peter-k/status-scrape/dev`
});
export const prisma = new Prisma();
