version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon-stretch-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - status-scrape-dependencies-{{ checksum "yarn.lock" }}
            - status-scrape-dependencies-
      - run: yarn install --pure-lockfile
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: status-scrape-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn run build
    persist_to_workspace:
      root: ~/repo
      paths: 'packages'
  test:
    docker:
      - image: circleci/node:carbon-stretch-browsers
    steps:
      - run: mkdir -p ~/repo && cd ~/repo
      - checkout
      - attach_workspace:
         at: ~/repo
      - run: yarn && yarn run test
      - store_test_results:
          path: './packages/functions/'
      - store_test_results:
          path: './packages/common/'
      - store_test_results:
          path: './packages/server/'
      - store_artifacts:
          path: './packages/functions/coverage'
      - store_artifacts:
          path: './packages/server/coverage'
      - store_artifacts:
          path: './packages/common/coverage'
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test:
        requires:
          - build
