/** Declaration file generated by dts-gen */

export = express_https_redirect;

declare function express_https_redirect(redirectLocalhost: any): any;

declare namespace express_https_redirect {
  const prototype: {};
}
