/** Declaration file generated by dts-gen */

export function withClientState(clientStateConfig: any, ...args: any[]): any;

export namespace withClientState {
    const prototype: {
    };

}

